export default Object.freeze({
  SIGNUP_SCREEN: 'Signup',
  LOGIN_SCREEN: 'Login',
  FORGOT_PASSWORD_SCREEN: 'Forgot password',
  RESET_PASSWORD_SCREEN: 'Reset password',
  VERIFY_SCREEN: 'Verify',
  CATEGORIES_SCREEN: 'Categories screen',
  SETTINGS_SCREEN: 'Settings screen',
  ADMIN_SCREEN: 'Admin',
  BASE_USER_SCREEN: 'User',
  CREATE_CATEGORIES_SCREEN: 'Create category',
  CATEGORIES_TAB: 'Categories',
  SETTINGS_TAB: 'Settings',
  UNEXPECTED_ERROR: 'An unexpected error occurred, please try again',
  SESSION_EXPIRED_ERROR: 'Your session has expired, please login to continue',
});
