export default Object.freeze({
  SIGNUP_SCREEN: 'Signup',
  LOGIN_SCREEN: 'Login',
  FORGOT_PASSWORD_SCREEN: 'Forgot password',
  RESET_PASSWORD_SCREEN: 'Reset password',
  VERIFY_SCREEN: 'Verify',
  CATEGORIES_SCREEN: 'Categories screen',
  SETTINGS_SCREEN: 'Settings screen',
  ADMIN_SCREEN: 'Admin',
  BASE_USER_SCREEN: 'User',
  CREATE_CATEGORY_SCREEN: 'Create category',
  UPDATE_CATEGORY_SCREEN: 'Update category',
  CATEGORIES_TAB: 'Categories',
  SETTINGS_TAB: 'Settings',
  UNEXPECTED_ERROR: 'An unexpected error occurred, please try again',
  SESSION_EXPIRED_ERROR: 'Your session has expired, please login to continue',
  INVALID_TOKEN: 'invalid token',
  DUMMY_SCREEN: 'Dummy',
  LOGBOOKS_TAB: 'Logbooks',
  REWARDS_TAB: 'Rewards',
  LOGBOOKS_SCREEN: 'Logbooks screen',
  CREATE_LOGBOOK_SCREEN: 'Create logbook',
  VISIBILITY_PUBLIC: 'public',
  LOGBOOK_SCREEN: 'Logbook screen',
  days: ['Sun', 'Mon', 'Tue', 'Wed', 'Thur', 'Fri', 'Sat'],
  months: [
    'Jan',
    'Feb',
    'Mar',
    'Apr',
    'May',
    'Jun',
    'Jul',
    'Aug',
    'Sept',
    'Oct',
    'Nov',
    'Dec',
  ],
});
